
import { EquipmentListing, EquipmentCategory } from './types';

export const MOCK_LISTINGS: EquipmentListing[] = [
  {
    id: '1',
    name: '2019 Caterpillar 320 GC',
    year: 2019,
    make: 'Caterpillar',
    model: '320 GC',
    category: EquipmentCategory.EXCAVATOR,
    location: 'Houston, TX',
    serialNumber: 'CAT0320GCJ12345',
    hours: 2450,
    weight: '48,281 lbs',
    netPower: '146 hp',
    maxDigDepth: '22.1 ft',
    engineModel: 'Cat C4.4 ACERT',
    buyPrice: 145000,
    rentDaily: 500,
    rentWeekly: 1800,
    rentMonthly: 4500,
    images: [
      'https://lh3.googleusercontent.com/aida-public/AB6AXuCiJFA11wMr4iJsV78pV4xArkQg8mnX2MaUbbq2kQPji_ZSvSTMCKhtGv25QMgQ3A6cyNXtQ6_AFvYDY_o4w1McKnGZQ29dkN7zijY3b6Iu9-EOklqw6ldVODMzc-N5eRUfAaZPPWwwQZyJEXUqkihzR8bHJCgVdgWbWY-ENdGx3SRNnJX2uV9ly5gjxXHGUnagN_180mHLMLFu6naXNWLW6W67vldYoStvnShpX6YJJYNJwSO0Fohdh62_rOY4ET4lbMLUfz8Vzb_Z',
      'https://lh3.googleusercontent.com/aida-public/AB6AXuAQmflaImYaiz2AOnTzkwBdH3axxrKxBNN4C-xZ0Sk4VqMd4VGsuCuHZZTgyCVleMWIGafKr2d8e7j2y-2SouM64b63ihugih1R9KduwAs4gMsXlBum9tkDOG8fqn8Dpr3mqs21rbv-hKpYTtda_JmS8hyjmmjrxwn2E9rm9qHg2cm6bjKxpLzrBia3rMgbmq9CyQZi1HMfzvrioZ3yiLFMS_2VJIMUNyB-ahwYgxyXZLIS-FrKZL3WOo59gxWkha07LitDYxQOagnk',
      'https://lh3.googleusercontent.com/aida-public/AB6AXuAbHezI8QjFJY5G2fq8CDPbpMi-07EE8pHWzLOgs73-dMaKueebY8we1uRoCHhSL0Ln56hgtNGi_amegxhu4wW2oxoEGNQi2LoOaqaMNEYARlre_jokydFbbX2yjqN6HjN8JtkVsaVch8QOkehRxqONsFbR4r4JD7HhY0IEjCznw9bMcAPjJfsHTTrnjZSvgZoUMHr5ddO3kSk5GzkVkHSTR3_fQsLjoPtmb2Gst6RhQjpPwxJ1FmRSJtJ0_9hUfvLJ8ZnAK6PxCWEu',
      'https://lh3.googleusercontent.com/aida-public/AB6AXuBCNqlw3_Tr4dBQGH92pirqlZRHTZy5YMMoF1q9O23cveI3zriKgsiUMVEUon-26O8Wo_qJgGmzU8Z839HVxTtr9rimJIebACKPlWDv3FXa58eO9rTNOGoDsTpBy6gLaoeOuV_gC5XBLpUJzF5v0PCvpBmg_JsMSP6luWHOlWAYIqc6GY4nxKXYTkNwAi7HOSM7cBZ9Qns_SfGxepz5oGaJktWrO5S9XSJfIW4NqDNlp1MYtYnistEx-XKqamweXFscp_2pthFA3YLD',
      'https://lh3.googleusercontent.com/aida-public/AB6AXuC1mfANFJPGex7lJKgwU_Pf_DmiADBliURHl0sHQdAQ0oJnWeSMJ4eSo0f7kEZA54GgvQYmb-wYK79433hzqsr7CHZNDOu7Ui1Noc5ORUv8BHCvJsRAvdyR_bRHomHtHlyPCJ-L_D5UkKUm5EbpsXfV2BYlHSsinBi8En5rjbZzeksEN4TFJPuItPhBfxzXgefjRuW897b_LphN6i-zCKV4OBbsViQE7j4KxCUT7EiuKnlp8nr0o9ncsETXAWcyvkKqR_8rxqlv0EqP'
    ],
    isReadyToWork: true,
    isVerifiedDealer: true,
    isAvailable: true,
    forSale: true,
    forRent: true,
    seller: {
      name: 'Texas Heavy Equipment Solutions',
      rating: 4.5,
      reviewsCount: 124,
      description: 'Premier dealer of heavy construction machinery in the Southern US. We perform rigorous 150-point inspections on all our sales and rental fleet units.',
      avatar: 'https://lh3.googleusercontent.com/aida-public/AB6AXuAV20MeEGl6aKW-sPeHojpNRItf7VtbH3-xvR5SchFVEtU-ttSL3A09XOi7jakLGWfdYSuIdfRwPK1Xt1hRt4n13tDJshWhaY_Ko4ZpUuczlEQtFp_Mmz_X3lYYdF3hvpHnP_WcwsTzKFc--hZTl-LtMOAaIGCOIDzyL7jSBizWzut8UOkCO0AlL7D7WYk_-ulsLNocxb6aoZiSaIJvYRuC4R0ADFY8OV2tJLe0YiUgJrHP-VrBSSJkjeQod3xINvrb5BPx_6DIvIt8'
    }
  },
  {
    id: '2',
    name: '2021 JLG Scissor Lift',
    year: 2021,
    make: 'JLG',
    model: '1930ES',
    category: EquipmentCategory.LIFT,
    location: 'Seattle, WA',
    serialNumber: 'JLG-12345678',
    hours: 450,
    buyPrice: 12500,
    rentDaily: 120,
    rentWeekly: 500,
    rentMonthly: 1500,
    images: ['https://lh3.googleusercontent.com/aida-public/AB6AXuAKHzyonFLkXxPYfb5g79JloSZpxSvILrFeYvayA90B8TWL1eU1nEjSZ04vj1CHiw48XwVhPeOVApg1mDYNOOIjyhxWSQ9h0PClShOG-8qjQON-OUWNiiDBOl4qVDGJv8giU2U50N-YjsQ7ilOW72KPEUJOv50HAzqFRVQISWalFS92n8kBT1sjsMeRxhXC6NA-aqmDhIn_HjUvWVOVhuHUgg3IG4lGPdNAMobgoTthxo6XsQ6dhZkuf2d4K7u6-SqXSNAYYMMXBVwp'],
    isReadyToWork: true,
    isVerifiedDealer: true,
    isAvailable: true,
    forSale: false,
    forRent: true,
    seller: {
      name: 'Northwest Lift & Rental',
      rating: 4.8,
      reviewsCount: 89,
      description: 'The Northwest\'s leading supplier for lift and aerial work platforms.',
      avatar: 'https://picsum.photos/seed/jlg/100/100'
    }
  },
  {
    id: '3',
    name: '2023 Komatsu D61PX',
    year: 2023,
    make: 'Komatsu',
    model: 'D61PX-24',
    category: EquipmentCategory.BULLDOZER,
    location: 'Austin, TX',
    serialNumber: 'KOM-78901234',
    hours: 120,
    buyPrice: 315000,
    rentDaily: 1200,
    rentWeekly: 4500,
    rentMonthly: 12000,
    images: ['https://lh3.googleusercontent.com/aida-public/AB6AXuAaoX4Glej2pO4wl3afQmxM6o4Pasv1M8SarVbvEwu8HiSGVZ7ubrjU4lHCPzt4G7SLu34PFu-MzXv7ORJ3OCccuZL1K0GoR08z7-e4qojlesI52-CJ3Mk8GdYoqF3fdiBBG2Uy8vk0tgzNwo6IH3UFHq53fS-TRILDfhptp_1ZKfxV5HmAgJvxa0Ys6CmmqHV1sGFJEUf_5eJge6Q8epC1qvu6u9FKdwj6s8rtDF_wCpqK6RQCD4JOGHm0BM9aWkk1sr7zzVyoIldH'],
    isReadyToWork: true,
    isVerifiedDealer: true,
    isAvailable: false,
    forSale: true,
    forRent: false,
    seller: {
      name: 'Lone Star Equipment',
      rating: 4.9,
      reviewsCount: 215,
      description: 'Trusted heavy equipment sales in the heart of Texas.',
      avatar: 'https://picsum.photos/seed/kom/100/100'
    }
  },
  {
    id: '4',
    name: 'Liebherr LTM 1060',
    year: 2020,
    make: 'Liebherr',
    model: 'LTM 1060-3.1',
    category: EquipmentCategory.CRANE,
    location: 'Denver, CO',
    serialNumber: 'LBH-55667788',
    hours: 5800,
    buyPrice: 480000,
    rentDaily: 1200,
    rentWeekly: 5000,
    rentMonthly: 18000,
    images: ['https://lh3.googleusercontent.com/aida-public/AB6AXuASqnajIAUwjQHPa59f8PEXhOD0uFKkjo00Rupf4WgugTw2OeHBCeQOTlyimJvJoL8COLJDKVU1sLVJYSKye0A_HZVT5oARbU4_ofy9zGWiZlMmtgebg2KKqYAQLbpcRdEalZcMU2_QikSGMILfUSbWBoGf8d6gwSBzg5A7zkPz_l2Rd8e-XbtYd12Ngw00gaplUK5dGz_4-VYRmIHJ-vcvFyuewC63VV15bDcE2X4XHzoynV_dGRNYoxtzGlSZjGqnGBJQHliQAvX1'],
    isReadyToWork: true,
    isVerifiedDealer: true,
    isAvailable: true,
    forSale: false,
    forRent: true,
    seller: {
      name: 'Mile High Crane Solutions',
      rating: 4.7,
      reviewsCount: 56,
      description: 'Specialized crane and hoisting solutions for high-altitude environments.',
      avatar: 'https://picsum.photos/seed/crane/100/100'
    }
  },
  {
    id: '5',
    name: 'Volvo A40G Hauler',
    year: 2018,
    make: 'Volvo',
    model: 'A40G',
    category: EquipmentCategory.DUMP_TRUCK,
    location: 'Phoenix, AZ',
    serialNumber: 'VOL-99887766',
    hours: 5100,
    buyPrice: 210000,
    rentDaily: 950,
    rentWeekly: 3800,
    rentMonthly: 11000,
    images: ['https://lh3.googleusercontent.com/aida-public/AB6AXuByILab8syDIxdpsQtdA9Lesy9m8g6viXVVFrqRZhHbLYcJvV2bO8G4Pc5eL-pwDFvPw9jj1z4lmJBJ3xMO570_H9nN-U0eTwfiFYy3MBdrqvYVe4meX7-TtVCVZKoSNHiXmnyTjj-ifTcnEZ-Ob5RYoHeCesBsWI5fpkEOrPqz_f2QU37NMQino__66JUQdzRlkozhFcePduQaW_FcwkPuPloWPq_UnfCns-zdQNdQxyPjc-QOcqrXbtMMYNqvwB-obMiqyUKGoXCU'],
    isReadyToWork: true,
    isVerifiedDealer: true,
    isAvailable: true,
    forSale: true,
    forRent: true,
    seller: {
      name: 'Desert Hauling Equipment',
      rating: 4.6,
      reviewsCount: 142,
      description: 'Your partner for earthmoving and hauling in the Southwest.',
      avatar: 'https://picsum.photos/seed/vol/100/100'
    }
  },
  {
    id: '6',
    name: 'Bobcat S650',
    year: 2022,
    make: 'Bobcat',
    model: 'S650',
    category: EquipmentCategory.LOADER,
    location: 'Orlando, FL',
    serialNumber: 'BOB-33445566',
    hours: 1200,
    buyPrice: 42500,
    rentDaily: 350,
    rentWeekly: 1400,
    rentMonthly: 4200,
    images: ['https://lh3.googleusercontent.com/aida-public/AB6AXuCAlwmw6ky8ZhxeGFfVbfvieHUOM6lw6JrkJsRNUL0InoTBwpEi0XdQ85BgwW6f3tn-Z5CXI7ydHXYwG-m_VHVahlN6wDpjQgVSr4TLT4KIwSp3qFIJSAHKvkQvYBVbPTmYAz8byGh_7AQDe-6-2qwivYm1oXfsJ1ZEBCfnCdPkx8sYDNmdsicMXsaidhv0hO1TcFyxfAKYEznVufAxAJv-HuCZKV2cgf8QajELJZ1gzWsxvPHVZoKNCLQCVm3M02yumQi9pFuyNBtJ'],
    isReadyToWork: true,
    isVerifiedDealer: false,
    isAvailable: true,
    forSale: true,
    forRent: false,
    seller: {
      name: 'Sunshine State Equipment',
      rating: 4.2,
      reviewsCount: 45,
      description: 'Quality compact loaders and attachments in Florida.',
      avatar: 'https://picsum.photos/seed/bob/100/100'
    }
  }
];
